In [2]:
import torch

In [7]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

Device refers to whether cuda is available or cpu
Thus above says if cuda available use it else cpu

In [8]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32,
                         device=device , requires_grad = True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)


Requires_grad refers to whether this is used for backprop or not  
Next we will see attributes of tensor

In [9]:
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
torch.float32
cuda:0
torch.Size([2, 3])


Other Init Types

In [11]:
# Uninitialized data
x = torch.empty(size=(3,3))
print(x)

# Zeros
x = torch.zeros((3,3))
print(x)

#uniform 0,1
x = torch.rand((3,3))
print(x)

# ones
x = torch.ones((3,3))
print(x)


#Identity Matrix (eye)
x = torch.eye(5,5)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.2823, 0.7646, 0.6517],
        [0.3155, 0.1649, 0.6234],
        [0.7620, 0.1132, 0.8057]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [16]:
#range
x = torch.arange(start=0, end = 4, step =1)
print(x)

#linspace
x = torch.linspace(start = 0, end = 1, steps = 10)
print(x)

#empty first then normally distributed
x = torch.empty(size=(1,5)).normal_(mean=0,std=1)
print(x)

#diagonal mtx
x = torch.diag(torch.ones(3))
#same as eye
print(x)

tensor([0, 1, 2, 3])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])
tensor([[ 0.0325, -2.3007, -0.4683,  0.3782,  0.6995]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [20]:
# init and convert to different types
tensor = torch.arange(4)
print(tensor.bool())

#to int16
print(tensor.short())

#to int64
print(tensor.long())

#to float16
print(tensor.half())

#to float32
print(tensor.float())

#to float64
print(tensor.double())

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [21]:
#Array to Tensor
import numpy as np
np_array =  np.zeros((5,5))
tensor = torch.from_numpy(np_array)
np_array_back = tensor.numpy()

### Tensor Math

In [22]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

In [ ]:
#Addition
z1 = torch.empty(3)
torch.add(x,y,out = z1)
z2 = torch.add(x,y)
z = x+y

